### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by brantje** [brantje/uptime#15]
- [ ] Make webPageTest multi user   
- [ ] Chrome / firefox desktop notifications
- [ ] When viewing a check that has no pings / events etc show a message instead of an empty graph.  
- [ ] Implement SB Admin https://github.com/IronSummitMedia/startbootstrap-sb-admin

**Cherry-pick**
- [ ] Hipchat notifications https://github.com/MichaelStephan/uptime/commit/3fc0c2f509f448c30297a0962fee717d0159032c
- [ ] VictorOps https://github.com/MichaelStephan/uptime/commit/df714c3fe10ce227d97dff95f15ccf717d7b9868
& https://github.com/MichaelStephan/uptime/commit/510c9c2ee7cf2c23563fe2caa5caaa886d45506f

- [ ] User / admin levels

Admins can
- [ ] Enable / disable plugins without restart
- [ ] Enable / disable pollers without restart
- [ ] Promote users to admin
- [ ] Wipe database / wipe all pings + history

Feel free to post your additions :smiley:
