### ISSUE TITLE
Personal todo list

### ISSUE THREAD

**Issue by brantje** [brantje/uptime#8]
- [x] Implemenet SPDY See: https://github.com/indutny/node-spdy
- [x] Hide statushud id when creating a check when statushub is not configured
- [ ] Make webPageTest multi user   
- [ ] Chrome / firefox desktop notifications
- [ ] When viewing a check that has no pings / events etc show a message instead of an empty graph.
Cherry-pick:
- [x] Fix IntervalBuilder crash during a check deletion https://github.com/MichaelStephan/uptime/commit/60409bc3820abbeb546efb0c9ed0dfbeb75d39b5
- [x] If no username set in auth then don't use it  https://github.com/hiddentao/uptime/commit/a71ec11905a6cbffd166b29e63926da0f9b37cd5
- [x] Auto connect on mongo connection loss https://github.com/MichaelStephan/uptime/commit/f49f6cc014d12b7344c81f24c49afd4e9fa21288
- [ ] Hipchat notifications https://github.com/MichaelStephan/uptime/commit/3fc0c2f509f448c30297a0962fee717d0159032c
- [ ] VictorOps https://github.com/MichaelStephan/uptime/commit/df714c3fe10ce227d97dff95f15ccf717d7b9868
& https://github.com/MichaelStephan/uptime/commit/510c9c2ee7cf2c23563fe2caa5caaa886d45506f
- [x] connections do not get freed upon errors https://github.com/MichaelStephan/uptime/commit/aa74247d0a7ac48db1a5362a03944aa943676bba
- [ ] SB Admin https://github.com/IronSummitMedia/startbootstrap-sb-admin

**Comment by animalillo** [comment]
[ ] on create account re check password

**Comment by traskat** [comment]
[ ] implement nrpe protocol to support nrpe daemon?

**Comment by tvvocold** [comment]
Check [cachet](https://news.ycombinator.com/item?id=9323488) out.
